const path = require('path');
const fs = require('fs');
const React = require('react');
const express = require('express');
const { Helmet } = require('react-helmet');
const ReactDOMServer = require('react-dom/server');
const { ServerStyleSheet } = require('styled-components');

const ServerApp = React.createFactory(
  require('../build/server.bundle.js').default,
);

const PORT = process.env.PORT || 3006;
const app = express();

app.use('/static', express.static(path.join(__dirname, '../build')));

app.get('/*', (req, res) => {
  const css = new ServerStyleSheet();

  const app = ReactDOMServer.renderToString(
    css.collectStyles(
      ServerApp({ url: req.url, context: {}, initialState: {} }),
    ),
  );

  const styleTags = css.getStyleTags();
  const helmet = Helmet.renderStatic();

  const html = `
  <!DOCTYPE html>
  <html>
    <head>
      ${styleTags}
      ${helmet.title.toString()}
      ${helmet.meta.toString()}
    </head>
    <body>
      <div id="root">${app}</div>
    </body>
    <!-- Client bundle generated by webpack -->
    <script src='/static/client.bundle.js'></script>
  </html>
  `;

  res.send(html);
});

app.listen(PORT, () => {
  console.log(`Server is listening on port ${PORT}`);
});
